-file("/home/bigbug/.asdf/installs/erlang/25.0.1/lib/parsetools-2.4/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/home/bigbug/forter/src/lexer.xrl", 57).

remove_lasts(N, List)->
    Size = length(List),
    lists:sublist(List, 1, Size-N).

to_logical(String)->
    case String of
        ".true." -> 1;
        ".false." -> 0
    end.
-file("/home/bigbug/.asdf/installs/erlang/25.0.1/lib/parsetools-2.4/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transition state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/home/bigbug/forter/src/lexer.erl", 317).
yystate() -> 132.

yystate(147, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(146, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(134, Ics, Line, Tlen+1, Action, Alen);
yystate(146, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(146, Ics, Line, Tlen+1, Action, Alen);
yystate(146, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,146};
yystate(145, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(143, Ics, Line, Tlen+1, Action, Alen);
yystate(145, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,145};
yystate(144, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(136, Ics, Line, Tlen+1, Action, Alen);
yystate(144, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,144};
yystate(143, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(131, Ics, Line, Tlen+1, Action, Alen);
yystate(143, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,143};
yystate(142, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, [110|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, [111|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, [109|Ics], Line, Tlen, _, _) ->
    yystate(138, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 108 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(142, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,142};
yystate(141, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(141, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(139, Ics, Line, Tlen+1, Action, Alen);
yystate(141, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(141, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 102 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(141, [C|Ics], Line, Tlen, Action, Alen) when C >= 104, C =< 111 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(141, [C|Ics], Line, Tlen, Action, Alen) when C >= 113 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(141, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,141};
yystate(140, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(139, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(127, Ics, Line, Tlen+1, Action, Alen);
yystate(139, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(139, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(139, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(139, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 111 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(139, [C|Ics], Line, Tlen, Action, Alen) when C >= 115 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(139, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,139};
yystate(138, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(138, [101|Ics], Line, Tlen, _, _) ->
    yystate(122, Ics, Line, Tlen+1, 19, Tlen);
yystate(138, [100|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(138, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(138, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(138, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(138, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(138, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(138, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(138, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(138, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(138, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,138};
yystate(137, [110|Ics], Line, Tlen, _, _) ->
    yystate(121, Ics, Line, Tlen+1, 18, Tlen);
yystate(137, [109|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 18, Tlen);
yystate(137, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(137, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(137, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(137, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(137, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(137, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,137};
yystate(136, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(120, Ics, Line, Tlen+1, Action, Alen);
yystate(136, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,136};
yystate(135, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(147, Ics, Line, Tlen+1, Action, Alen);
yystate(135, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,135};
yystate(134, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(118, Ics, Line, Tlen+1, Action, Alen);
yystate(134, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,134};
yystate(133, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(117, Ics, Line, Tlen+1, Action, Alen);
yystate(133, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(133, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,133};
yystate(132, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(116, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [107|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(137, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line+1, Tlen+1, Action, Alen);
yystate(132, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 99 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [C|Ics], Line, Tlen, Action, Alen) when C >= 109, C =< 111 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(132, [C|Ics], Line, Tlen, Action, Alen) when C >= 115, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(132, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,132};
yystate(131, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(115, Ics, Line, Tlen+1, Action, Alen);
yystate(131, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,131};
yystate(130, [110|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 21, Tlen);
yystate(130, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(66, Ics, Line, Tlen+1, 21, Tlen);
yystate(130, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 109 ->
    yystate(66, Ics, Line, Tlen+1, 21, Tlen);
yystate(130, [C|Ics], Line, Tlen, _, _) when C >= 111 ->
    yystate(66, Ics, Line, Tlen+1, 21, Tlen);
yystate(130, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line,130};
yystate(129, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(145, Ics, Line, Tlen+1, Action, Alen);
yystate(129, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,129};
yystate(128, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(128, [32|Ics], Line, Tlen, _, _) ->
    yystate(144, Ics, Line, Tlen+1, 18, Tlen);
yystate(128, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(128, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(128, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(128, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,128};
yystate(127, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(127, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(111, Ics, Line, Tlen+1, Action, Alen);
yystate(127, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(127, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 96 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(127, [C|Ics], Line, Tlen, Action, Alen) when C >= 98, C =< 111 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(127, [C|Ics], Line, Tlen, Action, Alen) when C >= 113 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(127, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,127};
yystate(126, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(126, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(126, [98|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(126, [97|Ics], Line, Tlen, _, _) ->
    yystate(142, Ics, Line, Tlen+1, 19, Tlen);
yystate(126, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(126, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 96 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(126, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,126};
yystate(125, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(125, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(141, Ics, Line, Tlen+1, Action, Alen);
yystate(125, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(125, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 110 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(125, [C|Ics], Line, Tlen, Action, Alen) when C >= 113 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(125, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,125};
yystate(124, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(140, Ics, Line, Tlen+1, Action, Alen);
yystate(124, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(124, Ics, Line, Tlen+1, Action, Alen);
yystate(124, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,124};
yystate(123, [99|Ics], Line, Tlen, _, _) ->
    yystate(100, Ics, Line, Tlen+1, 18, Tlen);
yystate(123, [97|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(123, [98|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(123, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(123, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(123, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(123, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(123, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,123};
yystate(122, [116|Ics], Line, Tlen, _, _) ->
    yystate(106, Ics, Line, Tlen+1, 19, Tlen);
yystate(122, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(122, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(122, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(122, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 115 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 117 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(122, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,122};
yystate(121, [116|Ics], Line, Tlen, _, _) ->
    yystate(105, Ics, Line, Tlen+1, 18, Tlen);
yystate(121, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(121, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(121, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(121, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(121, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(121, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,121};
yystate(120, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(104, Ics, Line, Tlen+1, Action, Alen);
yystate(120, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,120};
yystate(119, [68|Ics], Line, Tlen, _, _) ->
    yystate(135, Ics, Line, Tlen+1, 15, Tlen);
yystate(119, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(119, Ics, Line, Tlen+1, 15, Tlen);
yystate(119, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,119};
yystate(118, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(118, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,118};
yystate(117, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(101, Ics, Line, Tlen+1, Action, Alen);
yystate(117, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,117};
yystate(116, [101|Ics], Line, Tlen, _, _) ->
    yystate(100, Ics, Line, Tlen+1, 18, Tlen);
yystate(116, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(116, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,116};
yystate(115, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(99, Ics, Line, Tlen+1, Action, Alen);
yystate(115, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,115};
yystate(114, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(98, Ics, Line, Tlen+1, Action, Alen);
yystate(114, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(114, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(130, Ics, Line, Tlen+1, Action, Alen);
yystate(114, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(114, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 100 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(114, [C|Ics], Line, Tlen, Action, Alen) when C >= 102, C =< 109 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(114, [C|Ics], Line, Tlen, Action, Alen) when C >= 112 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(114, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,114};
yystate(113, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(129, Ics, Line, Tlen+1, Action, Alen);
yystate(113, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,113};
yystate(112, [101|Ics], Line, Tlen, _, _) ->
    yystate(128, Ics, Line, Tlen+1, 18, Tlen);
yystate(112, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(112, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,112};
yystate(111, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(111, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(111, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(111, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(111, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(111, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 108 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(111, [C|Ics], Line, Tlen, Action, Alen) when C >= 113 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(111, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,111};
yystate(110, [114|Ics], Line, Tlen, _, _) ->
    yystate(126, Ics, Line, Tlen+1, 19, Tlen);
yystate(110, [113|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(110, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(110, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(110, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(110, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 115 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(110, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,110};
yystate(109, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(125, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 111 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 115 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,109};
yystate(108, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(108, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(108, Ics, Line, Tlen+1, Action, Alen);
yystate(108, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 35 ->
    yystate(108, Ics, Line, Tlen+1, Action, Alen);
yystate(108, [C|Ics], Line, Tlen, Action, Alen) when C >= 37 ->
    yystate(108, Ics, Line, Tlen+1, Action, Alen);
yystate(108, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,108};
yystate(107, [105|Ics], Line, Tlen, _, _) ->
    yystate(123, Ics, Line, Tlen+1, 18, Tlen);
yystate(107, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(107, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,107};
yystate(106, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(106, [101|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 19, Tlen);
yystate(106, [100|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(106, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(106, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(106, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(106, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,106};
yystate(105, [101|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 18, Tlen);
yystate(105, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(105, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,105};
yystate(104, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(104, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,104};
yystate(103, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(119, Ics, Line, Tlen+1, Action, Alen);
yystate(103, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,103};
yystate(102, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(102, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,102};
yystate(101, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(101, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,101};
yystate(100, [97|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line, Tlen+1, 18, Tlen);
yystate(100, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(100, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,100};
yystate(99, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(99, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,99};
yystate(98, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(114, Ics, Line, Tlen+1, Action, Alen);
yystate(98, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(98, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 109 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(98, [C|Ics], Line, Tlen, Action, Alen) when C >= 111 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(98, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,98};
yystate(97, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(113, Ics, Line, Tlen+1, Action, Alen);
yystate(97, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,97};
yystate(96, [108|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 18, Tlen);
yystate(96, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(96, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,96};
yystate(95, [112|Ics], Line, Tlen, _, _) ->
    yystate(109, Ics, Line, Tlen+1, 1, Tlen);
yystate(95, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(93, Ics, Line, Tlen+1, 1, Tlen);
yystate(95, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 111 ->
    yystate(93, Ics, Line, Tlen+1, 1, Tlen);
yystate(95, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(93, Ics, Line, Tlen+1, 1, Tlen);
yystate(95, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,95};
yystate(94, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(94, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(94, [98|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(94, [97|Ics], Line, Tlen, _, _) ->
    yystate(110, Ics, Line, Tlen+1, 19, Tlen);
yystate(94, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(94, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 96 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(94, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,94};
yystate(93, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 111 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 113 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(93, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,93};
yystate(92, [36|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 20, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(108, Ics, Line, Tlen+1, 20, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 35 ->
    yystate(108, Ics, Line, Tlen+1, 20, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 37 ->
    yystate(108, Ics, Line, Tlen+1, 20, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,92};
yystate(91, [103|Ics], Line, Tlen, _, _) ->
    yystate(107, Ics, Line, Tlen+1, 18, Tlen);
yystate(91, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(91, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,91};
yystate(90, [114|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 19, Tlen);
yystate(90, [113|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(90, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(90, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(90, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(90, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 115 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,90};
yystate(89, [103|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 18, Tlen);
yystate(89, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(89, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,89};
yystate(88, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(88, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,88};
yystate(87, [46|Ics], Line, Tlen, _, _) ->
    yystate(103, Ics, Line, Tlen+1, 16, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(87, Ics, Line, Tlen+1, 16, Tlen);
yystate(87, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,87};
yystate(86, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(85, [112|Ics], Line, Tlen, _, _) ->
    yystate(97, Ics, Line, Tlen+1, 19, Tlen);
yystate(85, [99|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 19, Tlen);
yystate(85, [33|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 19, Tlen);
yystate(85, [32|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 19, Tlen);
yystate(85, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,85};
yystate(84, [108|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 18, Tlen);
yystate(84, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,84};
yystate(83, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(82, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(98, Ics, Line, Tlen+1, Action, Alen);
yystate(82, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(82, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(82, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 109 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(82, [C|Ics], Line, Tlen, Action, Alen) when C >= 112 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(82, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,82};
yystate(81, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(81, [33|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 18, Tlen);
yystate(81, [32|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 18, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,81};
yystate(80, [98|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line, Tlen+1, 18, Tlen);
yystate(80, [97|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(80, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,80};
yystate(79, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(77, [101|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 18, Tlen);
yystate(77, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,77};
yystate(76, [33|Ics], Line, Tlen, _, _) ->
    yystate(108, Ics, Line, Tlen+1, 9, Tlen);
yystate(76, [32|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 9, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,76};
yystate(75, [111|Ics], Line, Tlen, _, _) ->
    yystate(91, Ics, Line, Tlen+1, 18, Tlen);
yystate(75, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,75};
yystate(74, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 13, Tlen);
yystate(74, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 13, Tlen);
yystate(74, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(74, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,74};
yystate(73, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(72, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,72};
yystate(71, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(70, [111|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 18, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,70};
yystate(69, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(69, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(69, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(69, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,69};
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 7, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 7, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 7, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 7, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,68};
yystate(67, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(67, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,67};
yystate(66, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 109 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Tlen, Action, Alen) when C >= 111 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(66, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,66};
yystate(65, [100|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,65};
yystate(64, [117|Ics], Line, Tlen, _, _) ->
    yystate(80, Ics, Line, Tlen+1, 18, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(64, [33|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 18, Tlen);
yystate(64, [32|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 18, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,64};
yystate(63, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,63};
yystate(62, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(61, [114|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 18, Tlen);
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,61};
yystate(60, [33|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 19, Tlen);
yystate(60, [32|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 19, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(60, Ics, Line, Tlen+1, 19, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(60, Ics, Line, Tlen+1, 19, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 34 ->
    yystate(60, Ics, Line, Tlen+1, 19, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,60};
yystate(59, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,59};
yystate(58, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(58, [111|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 19, Tlen);
yystate(58, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(58, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(58, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 110 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,58};
yystate(57, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(57, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,57};
yystate(56, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(54, [33|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 18, Tlen);
yystate(54, [32|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 18, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,54};
yystate(53, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 12, Tlen);
yystate(53, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 12, Tlen);
yystate(53, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 12, Tlen);
yystate(53, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 12, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 12, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 12, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 12, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 12, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 12, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,53};
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,52};
yystate(51, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(51, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,51};
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, [33|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, [32|Ics], Line, Tlen, _, _) ->
    yystate(146, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,50};
yystate(49, [110|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,49};
yystate(48, [111|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 18, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,48};
yystate(47, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(45, [112|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 18, Tlen);
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,45};
yystate(44, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(43, [109|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 18, Tlen);
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,43};
yystate(42, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(42, [111|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(42, [110|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 19, Tlen);
yystate(42, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(42, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(42, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 109 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,42};
yystate(41, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(40, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,40};
yystate(39, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(38, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 115 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 117 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,38};
yystate(37, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, [101|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, [100|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,37};
yystate(36, [114|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 18, Tlen);
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,36};
yystate(35, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,35};
yystate(34, [116|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,34};
yystate(33, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(32, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(31, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(29, [108|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 18, Tlen);
yystate(29, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,29};
yystate(28, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(28, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,28};
yystate(27, [97|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 18, Tlen);
yystate(27, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,27};
yystate(26, [116|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 19, Tlen);
yystate(26, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(26, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(26, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(26, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 115 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 117 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,26};
yystate(25, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,25};
yystate(24, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(24, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,24};
yystate(23, [32|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 3, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,23};
yystate(22, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 110 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 112, C =< 115 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 117 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, [117|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 116 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 118 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,21};
yystate(20, [111|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,20};
yystate(19, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(19, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,19};
yystate(18, [105|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,18};
yystate(17, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,17};
yystate(16, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(13, [105|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,13};
yystate(12, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(12, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,12};
yystate(11, [114|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 18, Tlen);
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,11};
yystate(10, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(10, [105|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 19, Tlen);
yystate(10, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(10, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(10, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 104 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,10};
yystate(9, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(7, Ics, Line, Tlen+1, 3, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(7, Ics, Line, Tlen+1, 3, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,7};
yystate(6, [116|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 2, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, 2, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 115 ->
    yystate(38, Ics, Line, Tlen+1, 2, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 117 ->
    yystate(38, Ics, Line, Tlen+1, 2, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,6};
yystate(5, [112|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 19, Tlen);
yystate(5, [111|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(5, [110|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 19, Tlen);
yystate(5, [99|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 19, Tlen);
yystate(5, [33|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(5, [32|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 34, C =< 98 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 109 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 113 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,5};
yystate(4, [103|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,4};
yystate(3, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, [99|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [97|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [98|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 18, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,2};
yystate(1, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,1};
yystate(0, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, TokenLine) ->
    yyaction_0(TokenLine);
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, _, _, TokenLine) ->
    yyaction_2(TokenLine);
yyaction(3, _, _, TokenLine) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, _, _, _) ->
    yyaction_19();
yyaction(20, _, _, _) ->
    yyaction_20();
yyaction(21, _, _, _) ->
    yyaction_21();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 14).
yyaction_0(TokenLine) ->
     { token, { token_start, TokenLine } } .

-compile({inline,yyaction_1/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 15).
yyaction_1(TokenLine) ->
     { token, { token_end, TokenLine } } .

-compile({inline,yyaction_2/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 18).
yyaction_2(TokenLine) ->
     { token, { token_goto, TokenLine } } .

-compile({inline,yyaction_3/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 19).
yyaction_3(TokenLine) ->
     { token, { token_do, TokenLine } } .

-compile({inline,yyaction_4/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 22).
yyaction_4(TokenLine) ->
     { token, { token_assign, TokenLine } } .

-compile({inline,yyaction_5/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 23).
yyaction_5(TokenLine) ->
     { token, { token_double_colon, TokenLine } } .

-compile({inline,yyaction_6/2}).
-file("/home/bigbug/forter/src/lexer.xrl", 24).
yyaction_6(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_7/2}).
-file("/home/bigbug/forter/src/lexer.xrl", 27).
yyaction_7(TokenChars, TokenLine) ->
     { token, { token_type, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_8/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 30).
yyaction_8(TokenLine) ->
     { token, { token_comma, TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 31).
yyaction_9(TokenLine) ->
     { token, { token_endl, TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 32).
yyaction_10(TokenLine) ->
     { token, { token_bracket_open, TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 33).
yyaction_11(TokenLine) ->
     { token, { token_bracket_close, TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 34).
yyaction_12(TokenLine) ->
     { token, { token_endl, TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("/home/bigbug/forter/src/lexer.xrl", 37).
yyaction_13(TokenLine) ->
     { token, { parameter, TokenLine } } .

-compile({inline,yyaction_14/2}).
-file("/home/bigbug/forter/src/lexer.xrl", 40).
yyaction_14(TokenChars, TokenLine) ->
     { token, { double, TokenLine, list_to_float (remove_lasts (2, TokenChars)) } } .

-compile({inline,yyaction_15/2}).
-file("/home/bigbug/forter/src/lexer.xrl", 41).
yyaction_15(TokenChars, TokenLine) ->
     { token, { float, TokenLine, list_to_float (TokenChars) } } .

-compile({inline,yyaction_16/2}).
-file("/home/bigbug/forter/src/lexer.xrl", 42).
yyaction_16(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_17/2}).
-file("/home/bigbug/forter/src/lexer.xrl", 43).
yyaction_17(TokenChars, TokenLine) ->
     { token, { boolean, TokenLine, to_logical (TokenChars) } } .

-compile({inline,yyaction_18/2}).
-file("/home/bigbug/forter/src/lexer.xrl", 47).
yyaction_18(TokenChars, TokenLine) ->
     { token, { identifier, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_19/0}).
-file("/home/bigbug/forter/src/lexer.xrl", 50).
yyaction_19() ->
     skip_token .

-compile({inline,yyaction_20/0}).
-file("/home/bigbug/forter/src/lexer.xrl", 51).
yyaction_20() ->
     skip_token .

-compile({inline,yyaction_21/0}).
-file("/home/bigbug/forter/src/lexer.xrl", 52).
yyaction_21() ->
     skip_token .

-file("/home/bigbug/.asdf/installs/erlang/25.0.1/lib/parsetools-2.4/include/leexinc.hrl", 313).
